module.exports = [
{"status": 100, "description": "Continue", "class": "Informational"},
{"status": 101, "description": "Switching Protocols", "class": "Informational"},
{"status": 200, "description": "OK", "class": "Successful"},
{"status": 201, "description": "Created", "class": "Successful"},
{"status": 202, "description": "Accepted", "class": "Successful"},
{"status": 203, "description": "Non-Authoritative Information", "class": "Successful"},
{"status": 204, "description": "No Content", "class": "Successful"},
{"status": 205, "description": "Reset Content", "class": "Successful"},
{"status": 206, "description": "Partial Content", "class": "Successful"},
{"status": 300, "description": "Multiple Choices", "class": "Redirection"},
{"status": 301, "description": "Moved Permanently", "class": "Redirection"},
{"status": 302, "description": "Found", "class": "Redirection"},
{"status": 303, "description": "See Other", "class": "Redirection"},
{"status": 304, "description": "Not Modified", "class": "Redirection"},
{"status": 305, "description": "Use Proxy", "class": "Redirection"},
{"status": 307, "description": "Temporary Redirect", "class": "Redirection"},
{"status": 400, "description": "Bad Request", "class": "Client Error"},
{"status": 401, "description": "Unauthorized", "class": "Client Error"},
{"status": 402, "description": "Payment Required", "class": "Client Error"},
{"status": 403, "description": "Forbidden", "class": "Client Error"},
{"status": 404, "description": "Not Found", "class": "Client Error"},
{"status": 405, "description": "Method Not Allowed", "class": "Client Error"},
{"status": 406, "description": "Not Acceptable", "class": "Client Error"},
{"status": 407, "description": "Proxy Authentication Required", "class": "Client Error"},
{"status": 408, "description": "Request Timeout", "class": "Client Error"},
{"status": 409, "description": "Conflict", "class": "Client Error"},
{"status": 410, "description": "Gone", "class": "Client Error"},
{"status": 411, "description": "Length Required", "class": "Client Error"},
{"status": 412, "description": "Precondition Failed", "class": "Client Error"},
{"status": 413, "description": "Request Entity Too Large", "class": "Client Error"},
{"status": 414, "description": "Request-URI Too Long", "class": "Client Error"},
{"status": 415, "description": "Unsupported Media Type", "class": "Client Error"},
{"status": 416, "description": "Requested Range Not Satisfiable", "class": "Client Error"},
{"status": 417, "description": "Expectation Failed", "class": "Client Error"},
{"status": 500, "description": "Internal Server Error", "class": "Server Error"},
{"status": 501, "description": "Not Implemented", "class": "Server Error"},
{"status": 502, "description": "Bad Gateway", "class": "Server Error"},
{"status": 503, "description": "Service Unavailable", "class": "Server Error"},
{"status": 504, "description": "Gateway Timeout", "class": "Server Error"},
{"status": 505, "description": "HTTP Version Not Supported", "class": "Server Error"}
];
